apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    tier: db
    project: expense
  ports:
  - protocol: TCP
    port: 3306
    nodePort: 3306