apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
   name: service
   project: expense
spec:
  selector:
    component: backend
    project: expense
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: {{ .Values.service.tgport }}